### PR TITLE
Change Base Scale

### PR DESCRIPTION
**Pull request by Bradw-17**
Allows for clearer interpretation of difference from pre/post gyro filtering.

### CODE REVIEW

**Comment by bw1129** [comment]
Brad, do you mean the z-axis scale (I.e., color intensity)? I thought this was already modifiable from the command prompt, though it would be better if the min and max values were set same across plots by default, if that’s what you mean.

**Comment by Bradw-17** [comment]
Sorry, I should clarify that this is primarily for Mac/Linux users. I can speak from experience using a Mac, that the values are not modifiable prior to displaying the plots. 

There was a previous method I used that _kinda_ worked, but you had to change 3 larger sections of code, as well as changing the colour of the plots. Beyond that, they were only scaled  _better_, but still didnt match up with what scale most users would enter in Windows. (Also the scale the BF devs look for almost exclusively). 

This fixes that issue effeciently for Mac and Linux users. I am unsure of the effect it would have on Windows, so any testing would be appreciated. I would assume it would essentially change the default scale on all platforms.

**Comment by Smeat** [comment]
> I would assume it would essentially change the default scale on all platforms.

No it shouldn't. On Linux (at least for my machines) `str(np.shape(l))` returns "(4, 2)" and not "(4L, 2L)". Hence the string comparison fails.
```python
import numpy as np
print(np.shape(np.array([[1,2],[3,4],[5,6],[7,8]])))
```

Since `check_lims_list` fails, the limits will be determined based on the data.
Assuming the check also works on Windows (I would think so, but can't test it as I don't have access to a Windows installation) it won't change anything, since the check just passes as before.

**Comment by Bradw-17** [comment]
@Smeat Thanks for the input. I'm no programmer, so any suggestions you have are appreciated. This was suggested in a forum by someone using Linux, and they claimed it would work for Mac as well (which it did).

**Comment by bw1129** [comment]
I’d like to add something here. Time and again I see people post the PT pre and post filtered gyro noise plots where the prefiltered looks cleaner than the post, because the scales are not set the same by default. I realize there’s a colorbar for reference, but this so defeats the purpose of these plots, and is very misleading. I’ve found that [0 20] works well across all and gives the right impression as to how much real noise exists in each case. I recommend setting scales same across all panels.

**Pull request closed without merging**
