### PR TITLE
raw_input() is input() in Python 3

### PR DESCRIPTION
**Pull request by lostcontrol**
Also fixed a small typo.

### CODE REVIEW

**Comment by lostcontrol** [comment]
Tested with Ubuntu 18.04, works great, thanks.

**Comment by Plasmatree** [comment]
Sure, but input() does not work on 2.7.

raw_input() does not work at all on 3.x? Thought there was some downwards compatibility...

**Comment by lostcontrol** [comment]
Looking at the installation instructions, I thought you went for Python 3 only. No, raw_input doesn't work in Python 3. I can change it to make it work on both Python 2 and 3 if you prefer.

**Comment by lostcontrol** [comment]
Should now work on both Python 2 and 3.

**Comment by Plasmatree** [comment]
Six seems to be fine. I will add it after testing.

**Pull request merged**
